module

public import LeftPCI.FreeField.UniversalField
public import LeftPCI.OrePoly.Basic
public import Mathlib.Data.Matrix.Basic
public import Mathlib.Data.Matrix.Composition
public import Mathlib.LinearAlgebra.Matrix.Reindex
public import Mathlib.Algebra.CharP.Algebra
public import Mathlib.Algebra.Algebra.Rat
public import Mathlib.SetTheory.Cardinal.Basic
public import Mathlib.SetTheory.Cardinal.Subfield
public import Mathlib.Data.Finsupp.Encodable
public import Mathlib.Data.Rat.Encodable

@[expose] public section

namespace LeftPCI.Counterexample

universe u

/-! # Free fields; endomorphisms and derivations prescribed on generators

This is **Section 3** of the paper `paper/pci_counterexample.tex` (*PCI rings and V-domains are not left-right symmetric*), formalized statement by
statement.  Throughout, `k = ℚ`, `Y` is a set of generators, `ℚ⟨Y⟩ = FreeAlgebra ℚ Y` and
`φ : ℚ⟨Y⟩ →+* U` is a universal field of fractions (`FreeField.IsUniversalFieldOfFractions U φ`);
`U` is the *free field* `𝓕(Y)` of Definition 3.4 and `φ (FreeAlgebra.ι ℚ y)` is the generator
`y ∈ Y` viewed inside it.

* **Facts 3.1** (Cohn) are supplied by `LeftPCI/FreeField/`: (F1)+(F2)
  `FreeField.hasUniversalFieldOfFractions_freeAlgebra`, with the universal property
  `IsUniversalFieldOfFractions.exists_lift` / `.ext`; (F3) `IsUniversalFieldOfFractions.exists_extend_of_isHonest`.
* **Lemma 3.2** (`U` is generated by `ℚ⟨Y⟩`, hence by `Y`, as a division ring; countability):
  `subfield_eq_top_of_forall_gen`, `mem_of_forall_gen`, `countable`.
* **Lemma 3.3** (a homomorphism with a left inverse is honest): `FreeField.isHonest_of_leftInverse`.
* **Proposition 3.6** (endomorphisms and derivations prescribed on generators):
  existence `exists_pair` (Steps 1–3 of the proof: `isHonest_shiftAlg` is Step 1, the
  homomorphism `θ : ℚ⟨Y⟩ →+* M₂(U)` and its factorization through `U` are Step 2, the division
  subring `V` is Step 3); uniqueness `ringHom_ext_gen`, `oreDerivation_ext_gen`; the restriction
  clause `stable_closure`, `agree_closure` (stated for the subfield generated by any subset, which
  is what the paper's `𝓕(Y') ⊆ 𝓕(Y)` means by Lemma 3.5).
* **Lemma 3.7** (non-surjectivity): `gen_not_mem_range`.
* `FreeFieldOn Y` is a chosen free field on `Y : Type` (Definition 3.4), with `toFreeField` and
  `gen`.

The `M₂`-trick of Steps 2–3 is the argument of Cohn, *Free Ideal Rings and Localization in
General Rings* (2006), Thm 7.5.17, with a twist by `σ` inserted; see also *Skew Fields* (1995)
§2.1 (8)–(9).
-/

open FreeField

namespace FreeFieldExt

variable {Y : Type u}

/-- The algebra endomorphism `ŝ` of `ℚ⟨Y⟩` induced by a map `s` of generators. -/
noncomputable def shiftAlg (s : Y → Y) : FreeAlgebra ℚ Y →ₐ[ℚ] FreeAlgebra ℚ Y :=
  FreeAlgebra.lift ℚ (FreeAlgebra.ι ℚ ∘ s)

@[simp] theorem shiftAlg_ι (s : Y → Y) (y : Y) :
    shiftAlg s (FreeAlgebra.ι ℚ y) = FreeAlgebra.ι ℚ (s y) := by
  simp [shiftAlg]

/-- **Step 1 of Proposition 3.6**: an injective map of generators induces an honest endomorphism
of `ℚ⟨Y⟩` (it has a left inverse, Lemma 3.3). -/
theorem isHonest_shiftAlg {s : Y → Y} (hs : Function.Injective s) :
    IsHonest (shiftAlg s).toRingHom := by
  classical
  let π : FreeAlgebra ℚ Y →ₐ[ℚ] FreeAlgebra ℚ Y :=
    FreeAlgebra.lift ℚ (fun y => if h : ∃ y', s y' = y then FreeAlgebra.ι ℚ h.choose else 0)
  have hπ : ∀ y, π (shiftAlg s (FreeAlgebra.ι ℚ y)) = FreeAlgebra.ι ℚ y := by
    intro y
    have h : ∃ y', s y' = s y := ⟨y, rfl⟩
    simp only [shiftAlg_ι, π, FreeAlgebra.lift_ι_apply]
    split_ifs
    rw [hs h.choose_spec]
  have hπ' : π.comp (shiftAlg s) = AlgHom.id ℚ _ := FreeAlgebra.hom_ext (funext hπ)
  refine isHonest_of_leftInverse _ π.toRingHom fun r => ?_
  simpa using congrArg (fun g : FreeAlgebra ℚ Y →ₐ[ℚ] _ => g r) hπ'

/-- Ring homomorphisms out of `ℚ⟨Y⟩` agree if they agree on the generators. -/
theorem freeAlgebra_ringHom_ext {Z A : Type*} [Ring A] {f g : FreeAlgebra ℚ Z →+* A}
    (h : ∀ z, f (FreeAlgebra.ι ℚ z) = g (FreeAlgebra.ι ℚ z)) : f = g := by
  have hq : f.comp (algebraMap ℚ _) = g.comp (algebraMap ℚ _) := RingHom.ext_rat _ _
  ext r
  induction r using FreeAlgebra.induction with
  | grade0 q => exact congrArg (fun φ : ℚ →+* A => φ q) hq
  | grade1 z => exact h z
  | mul a b ha hb => rw [map_mul, map_mul, ha, hb]
  | add a b ha hb => rw [map_add, map_add, ha, hb]

/-- A ring homomorphism from a `ℚ`-algebra into a division ring forces characteristic `0`. -/
theorem charZero_of_ringHom {A L : Type*} [Ring A] [Algebra ℚ A] [DivisionRing L]
    (f : A →+* L) : CharZero L :=
  charZero_of_injective_ringHom (f.comp (algebraMap ℚ A)).injective

/-! ### Subfield lemmas (the restriction clause of Proposition 3.6) -/

section Subfield

variable {U : Type*} [DivisionRing U]

/-- The derivative of an inverse: `δ (u⁻¹) = −σ(u)⁻¹ δ(u) u⁻¹` (from `δ (u u⁻¹) = δ 1 = 0`). -/
theorem oreDerivation_map_inv {σ : U →+* U} (δ : OreDerivation U σ) (u : U) :
    δ u⁻¹ = -(σ u)⁻¹ * δ u * u⁻¹ := by
  rcases eq_or_ne u 0 with rfl | hu
  · simp
  have hσ : σ u ≠ 0 := (map_ne_zero σ).2 hu
  have h := δ.leibniz u u⁻¹
  rw [mul_inv_cancel₀ hu, δ.map_one] at h
  have h' : σ u * δ u⁻¹ = -(δ u * u⁻¹) := eq_neg_of_add_eq_zero_left h.symm
  calc δ u⁻¹ = (σ u)⁻¹ * (σ u * δ u⁻¹) := by rw [← mul_assoc, inv_mul_cancel₀ hσ, one_mul]
    _ = -(σ u)⁻¹ * δ u * u⁻¹ := by rw [h']; simp [mul_assoc]

/-- If `σ` and `δ` map a set `S` into the division subring generated by `S`, that subring is
stable under `σ` and `δ` (the set `W` in the proof of Proposition 3.6). -/
theorem stable_closure {σ : U →+* U} (δ : OreDerivation U σ) {S : Set U}
    (hσ : ∀ u ∈ S, σ u ∈ Subfield.closure S) (hδ : ∀ u ∈ S, δ u ∈ Subfield.closure S) :
    ∀ u ∈ Subfield.closure S, σ u ∈ Subfield.closure S ∧ δ u ∈ Subfield.closure S := by
  set C := Subfield.closure S
  let W : Subfield U :=
    { carrier := {u | u ∈ C ∧ σ u ∈ C ∧ δ u ∈ C}
      zero_mem' := by simp [C.zero_mem]
      one_mem' := by simp [C.one_mem, C.zero_mem]
      add_mem' := by
        rintro a b ⟨ha0, ha1, ha2⟩ ⟨hb0, hb1, hb2⟩
        simp only [Set.mem_ofPred_eq, map_add, OreDerivation.map_add]
        exact ⟨C.add_mem ha0 hb0, C.add_mem ha1 hb1, C.add_mem ha2 hb2⟩
      mul_mem' := by
        rintro a b ⟨ha0, ha1, ha2⟩ ⟨hb0, hb1, hb2⟩
        simp only [Set.mem_ofPred_eq, map_mul, δ.leibniz]
        exact ⟨C.mul_mem ha0 hb0, C.mul_mem ha1 hb1,
          C.add_mem (C.mul_mem ha1 hb2) (C.mul_mem ha2 hb0)⟩
      neg_mem' := by
        rintro a ⟨ha0, ha1, ha2⟩
        simp only [Set.mem_ofPred_eq, map_neg, OreDerivation.map_neg]
        exact ⟨C.neg_mem ha0, C.neg_mem ha1, C.neg_mem ha2⟩
      inv_mem' := by
        rintro a ⟨ha0, ha1, ha2⟩
        refine ⟨C.inv_mem ha0, ?_, ?_⟩
        · rw [map_inv₀]; exact C.inv_mem ha1
        · rw [oreDerivation_map_inv]
          exact C.mul_mem (C.mul_mem (C.neg_mem (C.inv_mem ha1)) ha2) (C.inv_mem ha0) }
  have hW : C ≤ W := Subfield.closure_le.2 fun u hu => ⟨Subfield.subset_closure hu, hσ u hu, hδ u hu⟩
  exact fun u hu => (hW hu).2

/-- Two pairs `(σ, δ)`, `(σ', δ')` that agree on `S` agree on the division subring generated by
`S` (uniqueness in Proposition 3.6: the equalizers are division subrings, using
`δ (u⁻¹) = −σ(u)⁻¹ δ(u) u⁻¹`). -/
theorem agree_closure {σ σ' : U →+* U} (δ : OreDerivation U σ) (δ' : OreDerivation U σ') {S : Set U}
    (hσ : ∀ u ∈ S, σ u = σ' u) (hδ : ∀ u ∈ S, δ u = δ' u) :
    ∀ u ∈ Subfield.closure S, σ u = σ' u ∧ δ u = δ' u := by
  let W : Subfield U :=
    { carrier := {u | σ u = σ' u ∧ δ u = δ' u}
      zero_mem' := by simp
      one_mem' := by simp
      add_mem' := by
        rintro a b ⟨ha1, ha2⟩ ⟨hb1, hb2⟩
        simp only [Set.mem_ofPred_eq, map_add, OreDerivation.map_add, ha1, ha2, hb1, hb2, and_self]
      mul_mem' := by
        rintro a b ⟨ha1, ha2⟩ ⟨hb1, hb2⟩
        simp only [Set.mem_ofPred_eq, map_mul, OreDerivation.leibniz, ha1, ha2, hb1, hb2, and_self]
      neg_mem' := by
        rintro a ⟨ha1, ha2⟩
        simp only [Set.mem_ofPred_eq, map_neg, OreDerivation.map_neg, ha1, ha2, and_self]
      inv_mem' := by
        rintro a ⟨ha1, ha2⟩
        simp only [Set.mem_ofPred_eq, map_inv₀, oreDerivation_map_inv, ha1, ha2, and_self] }
  have hW : Subfield.closure S ≤ W := Subfield.closure_le.2 fun u hu => ⟨hσ u hu, hδ u hu⟩
  exact fun u hu => hW hu

/-- A ring homomorphism maps the division subring generated by `S` into the division subring
generated by the image of `S`. -/
theorem map_mem_closure_image {V : Type*} [DivisionRing V] (α : U →+* V) {S : Set U} {u : U}
    (hu : u ∈ Subfield.closure S) : α u ∈ Subfield.closure (α '' S) := by
  rw [← RingHom.map_field_closure]
  exact ⟨u, hu, rfl⟩

end Subfield

/-! ### Auxiliary material for Lemma 3.2 and Steps 2–3 of Proposition 3.6 -/

/-- `ℚ⟨Y⟩` is countable when `Y` is (used for the countability clause of Lemma 3.2). -/
theorem countable_freeAlgebra (Y : Type u) [Countable Y] : Countable (FreeAlgebra ℚ Y) := by
  have : Countable (FreeMonoid Y) := inferInstanceAs (Countable (List Y))
  have : Countable (MonoidAlgebra ℚ (FreeMonoid Y)) :=
    Function.Injective.countable (f := MonoidAlgebra.coeff) fun a b h => by
      cases a; cases b; cases h; rfl
  exact FreeAlgebra.equivMonoidAlgebraFreeMonoid.toEquiv.injective.countable

/-- The `(i, j)` entry of a product of `2 × 2` matrices. -/
theorem mul_apply_fin_two {S : Type*} [Ring S] (M N : Matrix (Fin 2) (Fin 2) S) (i j : Fin 2) :
    (M * N) i j = M i 0 * N 0 j + M i 1 * N 1 j := by
  simp [Matrix.mul_apply, Fin.sum_univ_two]

/-- An upper triangular `2 × 2` matrix with unit diagonal entries is a unit. -/
theorem isUnit_of_upper_triangular {S : Type*} [Ring S] (M : Matrix (Fin 2) (Fin 2) S)
    (h10 : M 1 0 = 0) (h0 : IsUnit (M 0 0)) (h1 : IsUnit (M 1 1)) : IsUnit M := by
  obtain ⟨u, hu⟩ := h0
  obtain ⟨v, hv⟩ := h1
  have hM : M = !![(u : S), M 0 1; 0, (v : S)] := by
    rw [hu, hv, ← h10]; exact Matrix.eta_fin_two M
  rw [hM]
  generalize M 0 1 = b
  refine ⟨⟨_, !![↑u⁻¹, -(↑u⁻¹ * b * ↑v⁻¹); 0, ↑v⁻¹], ?_, ?_⟩, rfl⟩
  · rw [Matrix.mul_fin_two, Matrix.one_fin_two]
    simp [← mul_assoc]
  · rw [Matrix.mul_fin_two, Matrix.one_fin_two]
    simp [mul_assoc]

/-- The block transpose `M_n(M₂(S)) ≃ M₂(M_n(S))`. -/
noncomputable def blockSwap (S : Type*) [Ring S] (n : ℕ) :
    Matrix (Fin n) (Fin n) (Matrix (Fin 2) (Fin 2) S) ≃+*
      Matrix (Fin 2) (Fin 2) (Matrix (Fin n) (Fin n) S) :=
  ((Matrix.compRingEquiv (Fin n) (Fin 2) S).trans
    (Matrix.reindexRingEquiv S (Equiv.prodComm (Fin n) (Fin 2)))).trans
    (Matrix.compRingEquiv (Fin 2) (Fin n) S).symm

theorem blockSwap_apply {S : Type*} [Ring S] {n : ℕ}
    (M : Matrix (Fin n) (Fin n) (Matrix (Fin 2) (Fin 2) S))
    (i j : Fin 2) (a b : Fin n) : blockSwap S n M i j a b = M a b i j := rfl

/-- **Step 3 of Proposition 3.6**: the set `V` where `Θ : U → M₂(U)` has the expected
upper-triangular shape `!![σ u, *; 0, u]`, as a division subring. -/
def good {U : Type*} [DivisionRing U] (Θ : U →+* Matrix (Fin 2) (Fin 2) U) (σ : U →+* U) :
    Subfield U where
  carrier := {a | Θ a 1 0 = 0 ∧ Θ a 0 0 = σ a ∧ Θ a 1 1 = a}
  zero_mem' := by simp
  one_mem' := by simp
  add_mem' := by
    rintro a b ⟨ha1, ha2, ha3⟩ ⟨hb1, hb2, hb3⟩
    simp only [Set.mem_ofPred_eq, map_add, Matrix.add_apply, ha1, ha2, ha3, hb1, hb2, hb3,
      add_zero, and_self]
  mul_mem' := by
    rintro a b ⟨ha1, ha2, ha3⟩ ⟨hb1, hb2, hb3⟩
    simp only [Set.mem_ofPred_eq, map_mul]
    rw [mul_apply_fin_two, mul_apply_fin_two, mul_apply_fin_two]
    simp only [ha1, ha2, ha3, hb1, hb2, hb3, mul_zero, zero_mul, add_zero, zero_add, and_self]
  neg_mem' := by
    rintro a ⟨ha1, ha2, ha3⟩
    simp only [Set.mem_ofPred_eq, map_neg, Matrix.neg_apply, ha1, ha2, ha3, neg_zero, and_self]
  inv_mem' := by
    rintro a ⟨ha1, ha2, ha3⟩
    rcases eq_or_ne a 0 with rfl | ha
    · simp
    have hσa : σ a ≠ 0 := map_ne_zero _ |>.mpr ha
    have e1 : Θ a⁻¹ * Θ a = 1 := by rw [← map_mul, inv_mul_cancel₀ ha, map_one]
    have e2 : Θ a * Θ a⁻¹ = 1 := by rw [← map_mul, mul_inv_cancel₀ ha, map_one]
    have f10 := congr_fun (congr_fun e1 1) 0
    have f11 := congr_fun (congr_fun e2 1) 1
    have f00 := congr_fun (congr_fun e2 0) 0
    simp only [mul_apply_fin_two, ha1, ha2, ha3, mul_zero, add_zero, zero_mul, zero_add,
      Matrix.one_apply_eq, Matrix.one_apply_ne (show (1 : Fin 2) ≠ 0 by decide)] at f10 f11 f00
    have h10 : Θ a⁻¹ 1 0 = 0 := (mul_eq_zero.mp f10).resolve_right hσa
    rw [h10, mul_zero, add_zero] at f00
    refine ⟨h10, ?_, ?_⟩
    · rw [map_inv₀ σ]
      exact (eq_inv_of_mul_eq_one_right f00)
    · exact (eq_inv_of_mul_eq_one_right f11)

/-! ### Lemma 3.2 and Proposition 3.6 -/

section UniversalField

variable {U : Type u} [DivisionRing U] {φ : FreeAlgebra ℚ Y →+* U}
  (hφ : IsUniversalFieldOfFractions U φ)

include hφ

/-- **Lemma 3.2**: `U` is generated as a division ring by the generators `φ (ι y)`. -/
theorem subfield_eq_top_of_forall_gen {L : Subfield U} (hL : ∀ y, φ (FreeAlgebra.ι ℚ y) ∈ L) :
    L = ⊤ := by
  refine hφ.subfield_eq_top fun r => ?_
  induction r using FreeAlgebra.induction with
  | grade0 q =>
    rw [← RingHom.comp_apply, eq_ratCast]
    exact SubfieldClass.ratCast_mem L q
  | grade1 y => exact hL y
  | mul a b ha hb => rw [map_mul]; exact L.mul_mem ha hb
  | add a b ha hb => rw [map_add]; exact L.add_mem ha hb

theorem mem_of_forall_gen {L : Subfield U} (hL : ∀ y, φ (FreeAlgebra.ι ℚ y) ∈ L) (u : U) :
    u ∈ L := by
  rw [subfield_eq_top_of_forall_gen hφ hL]; exact Subfield.mem_top u

/-- **Lemma 3.2**, countability: the free field on a countable set is countable. -/
theorem countable [Countable Y] : Countable U := by
  have : Countable (FreeAlgebra ℚ Y) := countable_freeAlgebra Y
  have hs : Cardinal.mk (Set.range φ) ≤ Cardinal.aleph0 :=
    Cardinal.mk_le_aleph0_iff.2 (Set.countable_range φ).to_subtype
  have hcl : Cardinal.mk (Subfield.closure (Set.range φ)) ≤ Cardinal.aleph0 :=
    (Subfield.cardinalMk_closure_le_max _).trans (max_le hs le_rfl)
  have htop : Subfield.closure (Set.range φ) = ⊤ :=
    hφ.subfield_eq_top fun r => Subfield.subset_closure ⟨r, rfl⟩
  have : Countable (Subfield.closure (Set.range φ)) := Cardinal.mk_le_aleph0_iff.1 hcl
  exact Function.Surjective.countable (f := fun x : Subfield.closure (Set.range φ) => (x : U))
    fun a => ⟨⟨a, by rw [htop]; exact Subfield.mem_top a⟩, rfl⟩

/-- **Proposition 3.6, existence**: for an injective `s : Y → Y` and arbitrary values
`d : Y → U` there are an endomorphism `σ` of `U` and a `σ`-derivation `δ` with
`σ (y) = s y` and `δ (y) = d y` on the generators. -/
theorem exists_pair {s : Y → Y} (hs : Function.Injective s) (d : Y → U) :
    ∃ (σ : U →+* U) (δ : OreDerivation U σ),
      (∀ y, σ (φ (FreeAlgebra.ι ℚ y)) = φ (FreeAlgebra.ι ℚ (s y))) ∧
        ∀ y, δ (φ (FreeAlgebra.ι ℚ y)) = d y := by
  have : CharZero U := charZero_of_ringHom φ
  -- Step 1: `σ` extends `ŝ`
  obtain ⟨σ, hσ⟩ := hφ.exists_extend_of_isHonest (isHonest_shiftAlg hs)
  -- Step 2: `θ : ℚ⟨Y⟩ → M₂(U)`, `y ↦ !![s y, d y; 0, y]`
  let θ : FreeAlgebra ℚ Y →ₐ[ℚ] Matrix (Fin 2) (Fin 2) U :=
    FreeAlgebra.lift ℚ fun y => !![φ (FreeAlgebra.ι ℚ (s y)), d y; 0, φ (FreeAlgebra.ι ℚ y)]
  have hθι : ∀ y, θ (FreeAlgebra.ι ℚ y) =
      !![φ (FreeAlgebra.ι ℚ (s y)), d y; 0, φ (FreeAlgebra.ι ℚ y)] := fun y => by
    simp [θ]
  have hθ : ∀ a, θ a 1 0 = 0 ∧ θ a 0 0 = φ (shiftAlg s a) ∧ θ a 1 1 = φ a := by
    intro a
    induction a using FreeAlgebra.induction with
    | grade0 q =>
      have h1 : φ (algebraMap ℚ _ q) = (q : U) := by rw [← RingHom.comp_apply φ, eq_ratCast]
      have h2 : algebraMap ℚ U q = q := eq_ratCast _ q
      simp [Matrix.algebraMap_matrix_apply, h1, h2]
    | grade1 y => simp [hθι]
    | mul a b ha hb =>
      obtain ⟨ha1, ha2, ha3⟩ := ha
      obtain ⟨hb1, hb2, hb3⟩ := hb
      simp only [map_mul, mul_apply_fin_two, ha1, ha2, ha3, hb1, hb2, hb3, mul_zero, zero_mul,
        add_zero, zero_add, and_self]
    | add a b ha hb =>
      obtain ⟨ha1, ha2, ha3⟩ := ha
      obtain ⟨hb1, hb2, hb3⟩ := hb
      simp only [map_add, Matrix.add_apply, ha1, ha2, ha3, hb1, hb2, hb3, add_zero, and_self]
  -- `θ` is full-inverting
  have hfull : IsFullInverting θ.toRingHom := by
    intro n A hA
    rw [← isUnit_map_iff (blockSwap U n)]
    apply isUnit_of_upper_triangular
    · ext a b
      simp [blockSwap_apply, (hθ _).1]
    · have : blockSwap U n (A.map θ.toRingHom) 0 0 = (A.map (shiftAlg s).toRingHom).map φ := by
        ext a b
        simp [blockSwap_apply, (hθ _).2.1]
      rw [this]
      exact hφ.fullInverting n _ (isHonest_shiftAlg hs n A hA)
    · have : blockSwap U n (A.map θ.toRingHom) 1 1 = A.map φ := by
        ext a b
        simp [blockSwap_apply, (hθ _).2.2]
      rw [this]
      exact hφ.fullInverting n A hA
  -- factor `θ` through `U`
  obtain ⟨Θ, hΘ⟩ := hφ.exists_lift _ θ.toRingHom hfull
  have hΘφ : ∀ r, Θ (φ r) = θ r := fun r => RingHom.congr_fun hΘ r
  -- Step 3: `Θ` is upper triangular with diagonal `(σ u, u)` everywhere
  have hent : ∀ a, Θ a 1 0 = 0 ∧ Θ a 0 0 = σ a ∧ Θ a 1 1 = a := by
    intro a
    have hmem : a ∈ good Θ σ := by
      refine hφ.mem_of_forall (fun r => ?_) a
      change Θ (φ r) 1 0 = 0 ∧ Θ (φ r) 0 0 = σ (φ r) ∧ Θ (φ r) 1 1 = φ r
      rw [hΘφ, hσ]
      exact hθ r
    exact hmem
  refine ⟨σ, ⟨fun a => Θ a 0 1, fun a b => by simp, fun a b => ?_⟩, fun y => ?_, fun y => ?_⟩
  · rw [map_mul, mul_apply_fin_two, (hent a).2.1, (hent b).2.2]
  · rw [hσ]; simp
  · change Θ (φ (FreeAlgebra.ι ℚ y)) 0 1 = d y
    rw [hΘφ, hθι]
    simp

/-- **Proposition 3.6, uniqueness** for the endomorphism: two ring homomorphisms out of `U`
agreeing on the generators are equal. -/
theorem ringHom_ext_gen {V : Type u} [Ring V] {α β : U →+* V}
    (h : ∀ y, α (φ (FreeAlgebra.ι ℚ y)) = β (φ (FreeAlgebra.ι ℚ y))) : α = β :=
  hφ.ext V α β (freeAlgebra_ringHom_ext h)

/-- **Proposition 3.6, uniqueness** for the derivation. -/
theorem oreDerivation_ext_gen {σ : U →+* U} {δ δ' : OreDerivation U σ}
    (h : ∀ y, δ (φ (FreeAlgebra.ι ℚ y)) = δ' (φ (FreeAlgebra.ι ℚ y))) : δ = δ' := by
  have htop : Subfield.closure (Set.range fun y => φ (FreeAlgebra.ι ℚ y)) = ⊤ :=
    subfield_eq_top_of_forall_gen hφ fun y => Subfield.subset_closure ⟨y, rfl⟩
  have key := agree_closure δ δ' (S := Set.range fun y => φ (FreeAlgebra.ι ℚ y))
    (fun _ _ => rfl) (by rintro _ ⟨y, rfl⟩; exact h y)
  ext u
  exact (key u (by rw [htop]; exact Subfield.mem_top u)).2

-- `hs` is part of the paper's hypotheses but not needed for this direction.
set_option linter.unusedVariables false in
/-- **Lemma 3.7** (non-surjectivity): if `y₀` is not in the image of `s`, then the generator
`y₀` is not in the image of any endomorphism `σ` of `U` with `σ y = s y` on generators. -/
theorem gen_not_mem_range {s : Y → Y} (hs : Function.Injective s) {y₀ : Y}
    (hy₀ : y₀ ∉ Set.range s) {σ : U →+* U}
    (hσ : ∀ y, σ (φ (FreeAlgebra.ι ℚ y)) = φ (FreeAlgebra.ι ℚ (s y))) :
    φ (FreeAlgebra.ι ℚ y₀) ∉ Set.range σ := by
  classical
  -- the translation `y₀ ↦ y₀ + 1` of `ℚ⟨Y⟩` and its inverse
  let τA : FreeAlgebra ℚ Y →ₐ[ℚ] FreeAlgebra ℚ Y :=
    FreeAlgebra.lift ℚ fun y => if y = y₀ then FreeAlgebra.ι ℚ y + 1 else FreeAlgebra.ι ℚ y
  let πA : FreeAlgebra ℚ Y →ₐ[ℚ] FreeAlgebra ℚ Y :=
    FreeAlgebra.lift ℚ fun y => if y = y₀ then FreeAlgebra.ι ℚ y - 1 else FreeAlgebra.ι ℚ y
  have hτA : ∀ y, τA (FreeAlgebra.ι ℚ y) =
      if y = y₀ then FreeAlgebra.ι ℚ y + 1 else FreeAlgebra.ι ℚ y := fun y => by
    simp [τA]
  have hπA : ∀ y, πA (FreeAlgebra.ι ℚ y) =
      if y = y₀ then FreeAlgebra.ι ℚ y - 1 else FreeAlgebra.ι ℚ y := fun y => by
    simp [πA]
  have hπτ : πA.comp τA = AlgHom.id ℚ _ := FreeAlgebra.hom_ext <| funext fun y => by
    simp only [Function.comp_apply, AlgHom.comp_apply, AlgHom.id_apply, hτA]
    split_ifs with hy
    · rw [map_add, map_one, hπA]; simp [hy]
    · rw [hπA]; simp [hy]
  have hhon : IsHonest τA.toRingHom := isHonest_of_leftInverse _ πA.toRingHom fun r => by
    simpa using congrArg (fun g : FreeAlgebra ℚ Y →ₐ[ℚ] _ => g r) hπτ
  obtain ⟨τ, hτ⟩ := hφ.exists_extend_of_isHonest hhon
  -- `τ` fixes the division subring `C` generated by the `s y`
  set C := Subfield.closure (Set.range fun y => φ (FreeAlgebra.ι ℚ (s y)))
  have hC : C ≤ RingHom.eqLocusField τ (RingHom.id U) := by
    refine Subfield.closure_le.2 ?_
    rintro _ ⟨y, rfl⟩
    have hy : s y ≠ y₀ := fun h => hy₀ ⟨y, h⟩
    change τ (φ (FreeAlgebra.ι ℚ (s y))) = φ (FreeAlgebra.ι ℚ (s y))
    rw [hτ]
    simp [hτA, hy]
  -- `σ` maps everything into `C`
  have hσC : ∀ u, σ u ∈ C := by
    intro u
    refine mem_of_forall_gen hφ (L := C.comap σ) (fun y => ?_) u
    change σ (φ (FreeAlgebra.ι ℚ y)) ∈ C
    rw [hσ]
    exact Subfield.subset_closure ⟨y, rfl⟩
  rintro ⟨u, hu⟩
  have hfix : τ (σ u) = σ u := hC (hσC u)
  rw [hu, hτ] at hfix
  simp only [AlgHom.toRingHom_eq_coe, RingHom.coe_coe, hτA, ite_true, map_add, map_one,
    add_eq_left] at hfix
  exact one_ne_zero hfix

end UniversalField

/-! ### A chosen free field (Definition 3.4) -/

section Choice

variable (Y : Type)

/-- The free field `𝓕(Y)` on `Y` over `ℚ`, chosen once and for all (Facts 3.1 (F1), (F2)). -/
def FreeFieldOn : Type := (hasUniversalFieldOfFractions_freeAlgebra ℚ Y).choose

noncomputable instance : DivisionRing (FreeFieldOn Y) :=
  (hasUniversalFieldOfFractions_freeAlgebra ℚ Y).choose_spec.choose

/-- The embedding `ℚ⟨Y⟩ → 𝓕(Y)`. -/
noncomputable def toFreeField : FreeAlgebra ℚ Y →+* FreeFieldOn Y :=
  (hasUniversalFieldOfFractions_freeAlgebra ℚ Y).choose_spec.choose_spec.choose

theorem isUniversal_toFreeField : IsUniversalFieldOfFractions (FreeFieldOn Y) (toFreeField Y) :=
  (hasUniversalFieldOfFractions_freeAlgebra ℚ Y).choose_spec.choose_spec.choose_spec

/-- The generator `y ∈ Y` as an element of `𝓕(Y)`. -/
noncomputable def gen (y : Y) : FreeFieldOn Y := toFreeField Y (FreeAlgebra.ι ℚ y)

end Choice

end FreeFieldExt

end LeftPCI.Counterexample
