module

public import LeftPCI.FreeField.UniversalField
public import LeftPCI.OrePoly.Basic
public import Mathlib.Data.Matrix.Basic
public import Mathlib.Data.Matrix.Composition
public import Mathlib.LinearAlgebra.Matrix.Reindex
public import Mathlib.Algebra.CharP.Algebra
public import Mathlib.Algebra.Algebra.Rat
public import Mathlib.SetTheory.Cardinal.Basic
public import Mathlib.SetTheory.Cardinal.Subfield
public import Mathlib.Data.Finsupp.Encodable
public import Mathlib.Data.Rat.Encodable

@[expose] public section

namespace LeftPCI.Counterexample

universe u

/-! # Free fields; endomorphisms and derivations prescribed on generators

This is **Section 3** of the paper `paper/pci_counterexample.tex`, formalized
statement by statement.  Throughout, `k = ℚ`, `Y` is a set of generators, `ℚ⟨Y⟩ = FreeAlgebra ℚ Y`
and `φ : ℚ⟨Y⟩ →+* U` is a universal field of fractions
(`FreeField.IsUniversalFieldOfFractions U φ`); `U` is the *free field* `𝓕(Y)` on `Y` (the
paragraph after Theorem 3.1) and `φ (FreeAlgebra.ι ℚ y)` is the generator `y ∈ Y` viewed inside
it.

* **Theorem 3.1** (Cohn) is supplied by `LeftPCI/FreeField/`:
  `FreeField.hasUniversalFieldOfFractions_freeAlgebra`, with the universal property
  `IsUniversalFieldOfFractions.exists_lift` / `.ext`.
* **Lemma 3.2** (rigidity: two homomorphisms out of `U` agreeing on `ℚ⟨Y⟩` are equal) is
  `IsUniversalFieldOfFractions.ext`.
* **Lemma 3.3** (`U` is generated by `Y`; used only for countability): `countable`.
* **Lemma 3.4** (a homomorphism with a left inverse is honest, so composed with `φ` it is fully
  inverting): `isHonest_shiftAlg`, `FreeField.isHonest_of_leftInverse`, and
  `IsUniversalFieldOfFractions.exists_extend_of_isHonest` for the resulting extension.
* **Proposition 3.5** (endomorphisms and derivations prescribed on generators): `exists_pair`,
  via `θ : ℚ⟨Y⟩ →+* UT₂(U)` (`UT2`, `blockSwapUT`, `UT2.isUnit`) and rigidity for `π₂ ∘ Θ = id`.
* **Lemma 3.6** (non-surjectivity): `gen_not_mem_range`, by rigidity for `τ ∘ σ = σ`.
* `FreeFieldOn Y` is a chosen free field on `Y : Type`, with `toFreeField` and `gen`.

The triangular-matrix trick is the argument of Cohn, *Free Ideal Rings and Localization in
General Rings* (2006), Thm 7.5.17, with a twist by `σ` inserted; see also *Skew Fields* (1995)
§2.1 (8)–(9).
-/

open FreeField

namespace FreeFieldExt

variable {Y : Type u}

/-- The algebra endomorphism `ŝ` of `ℚ⟨Y⟩` induced by a map `s` of generators. -/
noncomputable def shiftAlg (s : Y → Y) : FreeAlgebra ℚ Y →ₐ[ℚ] FreeAlgebra ℚ Y :=
  FreeAlgebra.lift ℚ (FreeAlgebra.ι ℚ ∘ s)

@[simp] theorem shiftAlg_ι (s : Y → Y) (y : Y) :
    shiftAlg s (FreeAlgebra.ι ℚ y) = FreeAlgebra.ι ℚ (s y) := by
  simp [shiftAlg]

/-- **Step 1 of Proposition 3.5**: an injective map of generators induces an honest endomorphism
of `ℚ⟨Y⟩` (it has a left inverse, Lemma 3.4). -/
theorem isHonest_shiftAlg {s : Y → Y} (hs : Function.Injective s) :
    IsHonest (shiftAlg s).toRingHom := by
  classical
  let π : FreeAlgebra ℚ Y →ₐ[ℚ] FreeAlgebra ℚ Y :=
    FreeAlgebra.lift ℚ (fun y => if h : ∃ y', s y' = y then FreeAlgebra.ι ℚ h.choose else 0)
  have hπ : ∀ y, π (shiftAlg s (FreeAlgebra.ι ℚ y)) = FreeAlgebra.ι ℚ y := by
    intro y
    have h : ∃ y', s y' = s y := ⟨y, rfl⟩
    simp only [shiftAlg_ι, π, FreeAlgebra.lift_ι_apply]
    split_ifs
    rw [hs h.choose_spec]
  have hπ' : π.comp (shiftAlg s) = AlgHom.id ℚ _ := FreeAlgebra.hom_ext (funext hπ)
  refine isHonest_of_leftInverse _ π.toRingHom fun r => ?_
  simpa using congrArg (fun g : FreeAlgebra ℚ Y →ₐ[ℚ] _ => g r) hπ'

/-- A ring homomorphism from a `ℚ`-algebra into a division ring forces characteristic `0`. -/
theorem charZero_of_ringHom {A L : Type*} [Ring A] [Algebra ℚ A] [DivisionRing L]
    (f : A →+* L) : CharZero L :=
  charZero_of_injective_ringHom (f.comp (algebraMap ℚ A)).injective

/-! ### Auxiliary material for Lemma 3.3 and Steps 2–3 of Proposition 3.5 -/

/-- `ℚ⟨Y⟩` is countable when `Y` is (used for the countability clause of Lemma 3.3). -/
theorem countable_freeAlgebra (Y : Type u) [Countable Y] : Countable (FreeAlgebra ℚ Y) := by
  have : Countable (FreeMonoid Y) := inferInstanceAs (Countable (List Y))
  have : Countable (MonoidAlgebra ℚ (FreeMonoid Y)) :=
    Function.Injective.countable (f := MonoidAlgebra.coeff) fun a b h => by
      cases a; cases b; cases h; rfl
  exact FreeAlgebra.equivMonoidAlgebraFreeMonoid.toEquiv.injective.countable

/-- The `(i, j)` entry of a product of `2 × 2` matrices. -/
theorem mul_apply_fin_two {S : Type*} [Ring S] (M N : Matrix (Fin 2) (Fin 2) S) (i j : Fin 2) :
    (M * N) i j = M i 0 * N 0 j + M i 1 * N 1 j := by
  simp [Matrix.mul_apply, Fin.sum_univ_two]

/-- Ring homomorphisms out of `ℚ⟨Y⟩` agree if they agree on the generators. -/
theorem freeAlgebra_ringHom_ext {Z A : Type*} [Ring A] {f g : FreeAlgebra ℚ Z →+* A}
    (h : ∀ z, f (FreeAlgebra.ι ℚ z) = g (FreeAlgebra.ι ℚ z)) : f = g := by
  have hq : f.comp (algebraMap ℚ _) = g.comp (algebraMap ℚ _) := RingHom.ext_rat _ _
  ext r
  induction r using FreeAlgebra.induction with
  | grade0 q => exact congrArg (fun φ : ℚ →+* A => φ q) hq
  | grade1 z => exact h z
  | mul a b ha hb => rw [map_mul, map_mul, ha, hb]
  | add a b ha hb => rw [map_add, map_add, ha, hb]

/-- The ring `UT₂(S)` of upper triangular `2 × 2` matrices over `S` (proof of Proposition 3.5). -/
def UT2 (S : Type*) [Ring S] : Subring (Matrix (Fin 2) (Fin 2) S) where
  carrier := {M | M 1 0 = 0}
  zero_mem' := rfl
  one_mem' := by simp
  add_mem' := by
    intro a b ha hb
    change a 1 0 + b 1 0 = 0
    rw [show a 1 0 = 0 from ha, show b 1 0 = 0 from hb, add_zero]
  mul_mem' := by
    intro a b ha hb
    change (a * b) 1 0 = 0
    rw [mul_apply_fin_two, show a 1 0 = 0 from ha, show b 1 0 = 0 from hb, zero_mul, mul_zero,
      add_zero]
  neg_mem' := by
    intro a ha
    change -a 1 0 = 0
    rw [show a 1 0 = 0 from ha, neg_zero]

theorem UT2.apply_one_zero {S : Type*} [Ring S] (M : UT2 S) : M.1 1 0 = 0 := M.2

/-- The diagonal entries `π₁, π₂ : UT₂(S) → S` are ring homomorphisms. -/
def UT2.diag (S : Type*) [Ring S] (i : Fin 2) : UT2 S →+* S where
  toFun M := M.1 i i
  map_one' := by simp
  map_mul' M N := by
    change (M.1 * N.1) i i = M.1 i i * N.1 i i
    fin_cases i <;> simp [mul_apply_fin_two, UT2.apply_one_zero]
  map_zero' := rfl
  map_add' _ _ := rfl

/-- An element of `UT₂(S)` with unit diagonal entries is a unit of `UT₂(S)`. -/
theorem UT2.isUnit {S : Type*} [Ring S] (M : UT2 S) (h0 : IsUnit (M.1 0 0))
    (h1 : IsUnit (M.1 1 1)) : IsUnit M := by
  obtain ⟨M, h10⟩ := M
  change M 1 0 = 0 at h10
  obtain ⟨u, hu⟩ := h0
  obtain ⟨v, hv⟩ := h1
  change (u : S) = M 0 0 at hu
  change (v : S) = M 1 1 at hv
  have hM : M = !![(u : S), M 0 1; 0, (v : S)] := by
    rw [hu, hv, ← h10]; exact (Matrix.eta_fin_two M)
  generalize M 0 1 = b at hM
  subst hM
  refine ⟨⟨⟨_, h10⟩, ⟨!![↑u⁻¹, -(↑u⁻¹ * b * ↑v⁻¹); 0, ↑v⁻¹], by
    change (_ : Matrix (Fin 2) (Fin 2) S) 1 0 = 0; simp⟩, ?_, ?_⟩, rfl⟩
  · apply Subtype.ext
    change !![(u : S), b; 0, (v : S)] * !![↑u⁻¹, -(↑u⁻¹ * b * ↑v⁻¹); 0, ↑v⁻¹] = 1
    rw [Matrix.mul_fin_two, Matrix.one_fin_two]
    simp [← mul_assoc]
  · apply Subtype.ext
    change !![↑u⁻¹, -(↑u⁻¹ * b * ↑v⁻¹); 0, ↑v⁻¹] * !![(u : S), b; 0, (v : S)] = 1
    rw [Matrix.mul_fin_two, Matrix.one_fin_two]
    simp [mul_assoc]

/-- The block transpose `M_n(M₂(S)) ≃ M₂(M_n(S))`. -/
noncomputable def blockSwap (S : Type*) [Ring S] (n : ℕ) :
    Matrix (Fin n) (Fin n) (Matrix (Fin 2) (Fin 2) S) ≃+*
      Matrix (Fin 2) (Fin 2) (Matrix (Fin n) (Fin n) S) :=
  ((Matrix.compRingEquiv (Fin n) (Fin 2) S).trans
    (Matrix.reindexRingEquiv S (Equiv.prodComm (Fin n) (Fin 2)))).trans
    (Matrix.compRingEquiv (Fin 2) (Fin n) S).symm

theorem blockSwap_apply {S : Type*} [Ring S] {n : ℕ}
    (M : Matrix (Fin n) (Fin n) (Matrix (Fin 2) (Fin 2) S))
    (i j : Fin 2) (a b : Fin n) : blockSwap S n M i j a b = M a b i j := rfl

/-- Regrouping rows and columns restricts to `M_n(UT₂(S)) ≃ UT₂(M_n(S))`. -/
noncomputable def blockSwapUT (S : Type*) [Ring S] (n : ℕ) :
    Matrix (Fin n) (Fin n) (UT2 S) ≃+* UT2 (Matrix (Fin n) (Fin n) S) where
  toFun X := ⟨blockSwap S n (X.map (UT2 S).subtype), by
    change blockSwap S n _ 1 0 = 0
    ext a b
    exact (X a b).2⟩
  invFun Y := fun a b => ⟨fun i j => Y.1 i j a b, by
    change Y.1 1 0 a b = 0
    rw [UT2.apply_one_zero]; rfl⟩
  left_inv X := by ext a b : 2; rfl
  right_inv Y := by ext : 1; rfl
  map_mul' X Y := by
    apply Subtype.ext
    change blockSwap S n ((X * Y).map (UT2 S).subtype) = _
    rw [Matrix.map_mul, map_mul]; rfl
  map_add' X Y := by
    apply Subtype.ext
    change blockSwap S n ((X + Y).map (UT2 S).subtype) = _
    rw [Matrix.map_add _ (map_add (UT2 S).subtype), map_add]; rfl

theorem blockSwapUT_apply {S : Type*} [Ring S] {n : ℕ} (X : Matrix (Fin n) (Fin n) (UT2 S))
    (i j : Fin 2) (a b : Fin n) : (blockSwapUT S n X).1 i j a b = (X a b).1 i j := rfl

/-! ### Lemma 3.3 and Proposition 3.5 -/

section UniversalField

variable {U : Type u} [DivisionRing U] {φ : FreeAlgebra ℚ Y →+* U}
  (hφ : IsUniversalFieldOfFractions U φ)

include hφ

/-- **Lemma 3.3**, countability: the free field on a countable set is countable. -/
theorem countable [Countable Y] : Countable U := by
  have : Countable (FreeAlgebra ℚ Y) := countable_freeAlgebra Y
  have hs : Cardinal.mk (Set.range φ) ≤ Cardinal.aleph0 :=
    Cardinal.mk_le_aleph0_iff.2 (Set.countable_range φ).to_subtype
  have hcl : Cardinal.mk (Subfield.closure (Set.range φ)) ≤ Cardinal.aleph0 :=
    (Subfield.cardinalMk_closure_le_max _).trans (max_le hs le_rfl)
  have htop : Subfield.closure (Set.range φ) = ⊤ :=
    hφ.subfield_eq_top fun r => Subfield.subset_closure ⟨r, rfl⟩
  have : Countable (Subfield.closure (Set.range φ)) := Cardinal.mk_le_aleph0_iff.1 hcl
  exact Function.Surjective.countable (f := fun x : Subfield.closure (Set.range φ) => (x : U))
    fun a => ⟨⟨a, by rw [htop]; exact Subfield.mem_top a⟩, rfl⟩

/-- **Proposition 3.5**: for an injective `s : Y → Y` and arbitrary values `d : Y → U` there are an
endomorphism `σ` of `U` and a `σ`-derivation `δ` with `σ (y) = s y` and `δ (y) = d y` on the
generators. -/
theorem exists_pair {s : Y → Y} (hs : Function.Injective s) (d : Y → U) :
    ∃ (σ : U →+* U) (δ : OreDerivation U σ),
      (∀ y, σ (φ (FreeAlgebra.ι ℚ y)) = φ (FreeAlgebra.ι ℚ (s y))) ∧
        ∀ y, δ (φ (FreeAlgebra.ι ℚ y)) = d y := by
  have : CharZero U := charZero_of_ringHom φ
  -- `θ : ℚ⟨Y⟩ → UT₂(U)`, `y ↦ !![s y, d y; 0, y]`
  let θ : FreeAlgebra ℚ Y →ₐ[ℚ] Matrix (Fin 2) (Fin 2) U :=
    FreeAlgebra.lift ℚ fun y => !![φ (FreeAlgebra.ι ℚ (s y)), d y; 0, φ (FreeAlgebra.ι ℚ y)]
  have hθι : ∀ y, θ (FreeAlgebra.ι ℚ y) =
      !![φ (FreeAlgebra.ι ℚ (s y)), d y; 0, φ (FreeAlgebra.ι ℚ y)] := fun y => by
    simp [θ]
  have hθ : ∀ a, θ a 1 0 = 0 ∧ θ a 0 0 = φ (shiftAlg s a) ∧ θ a 1 1 = φ a := by
    intro a
    induction a using FreeAlgebra.induction with
    | grade0 q =>
      have h1 : φ (algebraMap ℚ _ q) = (q : U) := by rw [← RingHom.comp_apply φ, eq_ratCast]
      have h2 : algebraMap ℚ U q = q := eq_ratCast _ q
      simp [Matrix.algebraMap_matrix_apply, h1, h2]
    | grade1 y => simp [hθι]
    | mul a b ha hb =>
      obtain ⟨ha1, ha2, ha3⟩ := ha
      obtain ⟨hb1, hb2, hb3⟩ := hb
      simp only [map_mul, mul_apply_fin_two, ha1, ha2, ha3, hb1, hb2, hb3, mul_zero, zero_mul,
        add_zero, zero_add, and_self]
    | add a b ha hb =>
      obtain ⟨ha1, ha2, ha3⟩ := ha
      obtain ⟨hb1, hb2, hb3⟩ := hb
      simp only [map_add, Matrix.add_apply, ha1, ha2, ha3, hb1, hb2, hb3, add_zero, and_self]
  let θ' : FreeAlgebra ℚ Y →+* UT2 U := θ.toRingHom.codRestrict (UT2 U) fun a => (hθ a).1
  -- `θ` is fully inverting into `UT₂(U)`: the diagonal blocks `ŝ(A)` and `A` are invertible
  have hfull : IsFullInverting θ' := by
    intro n A hA
    rw [← isUnit_map_iff (blockSwapUT U n)]
    apply UT2.isUnit
    · have : (blockSwapUT U n (A.map θ')).1 0 0 = (A.map (shiftAlg s).toRingHom).map φ := by
        ext a b
        simp [blockSwapUT_apply, θ', (hθ _).2.1]
      rw [this]
      exact hφ.fullInverting n _ (isHonest_shiftAlg hs n A hA)
    · have : (blockSwapUT U n (A.map θ')).1 1 1 = A.map φ := by
        ext a b
        simp [blockSwapUT_apply, θ', (hθ _).2.2]
      rw [this]
      exact hφ.fullInverting n A hA
  obtain ⟨Θ, hΘ⟩ := hφ.exists_lift _ θ' hfull
  have hΘφ : ∀ r, Θ (φ r) = θ' r := fun r => RingHom.congr_fun hΘ r
  -- rigidity: `π₂ ∘ Θ = id`
  have h11 : (UT2.diag U 1).comp Θ = RingHom.id U :=
    hφ.ext U _ _ (RingHom.ext fun r => by
      change (Θ (φ r)).1 1 1 = φ r
      rw [hΘφ]; exact (hθ r).2.2)
  have h11' : ∀ b, (Θ b).1 1 1 = b := fun b => RingHom.congr_fun h11 b
  refine ⟨(UT2.diag U 0).comp Θ, ⟨fun a => (Θ a).1 0 1, fun a b => by simp, fun a b => ?_⟩,
    fun y => ?_, fun y => ?_⟩
  · change (Θ (a * b)).1 0 1 = (Θ a).1 0 0 * (Θ b).1 0 1 + (Θ a).1 0 1 * b
    rw [map_mul, Subring.coe_mul, mul_apply_fin_two, h11']
  · change (Θ (φ (FreeAlgebra.ι ℚ y))).1 0 0 = _
    rw [hΘφ]
    change θ (FreeAlgebra.ι ℚ y) 0 0 = _
    rw [(hθ _).2.1, shiftAlg_ι]
  · change (Θ (φ (FreeAlgebra.ι ℚ y))).1 0 1 = d y
    rw [hΘφ]
    change θ (FreeAlgebra.ι ℚ y) 0 1 = d y
    rw [hθι]
    simp

-- `hs` is part of the paper's hypotheses but not needed for this direction.
set_option linter.unusedVariables false in
/-- **Lemma 3.6** (non-surjectivity): if `y₀` is not in the image of `s`, then the generator
`y₀` is not in the image of any endomorphism `σ` of `U` with `σ y = s y` on generators. -/
theorem gen_not_mem_range {s : Y → Y} (hs : Function.Injective s) {y₀ : Y}
    (hy₀ : y₀ ∉ Set.range s) {σ : U →+* U}
    (hσ : ∀ y, σ (φ (FreeAlgebra.ι ℚ y)) = φ (FreeAlgebra.ι ℚ (s y))) :
    φ (FreeAlgebra.ι ℚ y₀) ∉ Set.range σ := by
  classical
  -- the translation `y₀ ↦ y₀ + 1` of `ℚ⟨Y⟩` and its inverse
  let τA : FreeAlgebra ℚ Y →ₐ[ℚ] FreeAlgebra ℚ Y :=
    FreeAlgebra.lift ℚ fun y => if y = y₀ then FreeAlgebra.ι ℚ y + 1 else FreeAlgebra.ι ℚ y
  let πA : FreeAlgebra ℚ Y →ₐ[ℚ] FreeAlgebra ℚ Y :=
    FreeAlgebra.lift ℚ fun y => if y = y₀ then FreeAlgebra.ι ℚ y - 1 else FreeAlgebra.ι ℚ y
  have hτA : ∀ y, τA (FreeAlgebra.ι ℚ y) =
      if y = y₀ then FreeAlgebra.ι ℚ y + 1 else FreeAlgebra.ι ℚ y := fun y => by
    simp [τA]
  have hπA : ∀ y, πA (FreeAlgebra.ι ℚ y) =
      if y = y₀ then FreeAlgebra.ι ℚ y - 1 else FreeAlgebra.ι ℚ y := fun y => by
    simp [πA]
  have hπτ : πA.comp τA = AlgHom.id ℚ _ := FreeAlgebra.hom_ext <| funext fun y => by
    simp only [Function.comp_apply, AlgHom.comp_apply, AlgHom.id_apply, hτA]
    split_ifs with hy
    · rw [map_add, map_one, hπA]; simp [hy]
    · rw [hπA]; simp [hy]
  have hhon : IsHonest τA.toRingHom := isHonest_of_leftInverse _ πA.toRingHom fun r => by
    simpa using congrArg (fun g : FreeAlgebra ℚ Y →ₐ[ℚ] _ => g r) hπτ
  obtain ⟨τ, hτ⟩ := hφ.exists_extend_of_isHonest hhon
  -- rigidity: `τ ∘ σ = σ`, since both agree on `ℚ⟨Y⟩`
  have hτσ : τ.comp σ = σ := hφ.ext U _ _ (freeAlgebra_ringHom_ext fun y => by
    have hy : s y ≠ y₀ := fun h => hy₀ ⟨y, h⟩
    simp only [RingHom.comp_apply, hσ, hτ, AlgHom.toRingHom_eq_coe, RingHom.coe_coe, hτA, hy,
      ite_false])
  rintro ⟨u, hu⟩
  have hfix : τ (σ u) = σ u := RingHom.congr_fun hτσ u
  rw [hu, hτ] at hfix
  simp only [AlgHom.toRingHom_eq_coe, RingHom.coe_coe, hτA, ite_true, map_add, map_one,
    add_eq_left] at hfix
  exact one_ne_zero hfix

end UniversalField

/-! ### A chosen free field (the free field `𝓕(Y)` of Section 3) -/

section Choice

variable (Y : Type)

/-- The free field `𝓕(Y)` on `Y` over `ℚ`, chosen once and for all (Theorem 3.1). -/
def FreeFieldOn : Type := (hasUniversalFieldOfFractions_freeAlgebra ℚ Y).choose

noncomputable instance : DivisionRing (FreeFieldOn Y) :=
  (hasUniversalFieldOfFractions_freeAlgebra ℚ Y).choose_spec.choose

/-- The embedding `ℚ⟨Y⟩ → 𝓕(Y)`. -/
noncomputable def toFreeField : FreeAlgebra ℚ Y →+* FreeFieldOn Y :=
  (hasUniversalFieldOfFractions_freeAlgebra ℚ Y).choose_spec.choose_spec.choose

theorem isUniversal_toFreeField : IsUniversalFieldOfFractions (FreeFieldOn Y) (toFreeField Y) :=
  (hasUniversalFieldOfFractions_freeAlgebra ℚ Y).choose_spec.choose_spec.choose_spec

/-- The generator `y ∈ Y` as an element of `𝓕(Y)`. -/
noncomputable def gen (y : Y) : FreeFieldOn Y := toFreeField Y (FreeAlgebra.ι ℚ y)

end Choice

end FreeFieldExt

end LeftPCI.Counterexample
