module

public import LeftPCI.Counterexample.FreeFieldExt
public import LeftPCI.Counterexample.Adjoin
public import LeftPCI.Counterexample.OreExtension
public import Mathlib.Data.Finsupp.Encodable
public import Mathlib.Data.Nat.Pairing

@[expose] public section

namespace LeftPCI.Counterexample

/-! # The construction: proof of Theorem 2.5 (Section 5 of the paper, variant of Remark 5.2)

This file formalizes **Section 5** of the paper `paper/pci_counterexample.tex` (*PCI rings and V-domains are not left-right symmetric*): Construction
5.1 in the **fixed-symbol variant of Remark 5.2**, and the proof of **Theorem 2.5** (stated in §2,
proved in §5), with `k = ℚ`.

Remark 5.2 fixes all symbols in advance: `Y = Y₀ ⊔ (ℕ × ℕ)` with `s` the shift on `Y₀` and the
identity on `ℕ × ℕ`, and one free field `U = 𝓕(Y)`; all the pairs `(σ_i, δ_i)` are pairs on the
whole of `U`, determined by `(s, d_i)` via Proposition 3.6.  The dictionary is:

| paper (Remark 5.2)                         | Lean                                     |
|--------------------------------------------|------------------------------------------|
| `Y = Y₀ ⊔ (ℕ × ℕ)`, `s`, `U = 𝓕(Y)`        | `Y`, `s`, `U` (`y_j = Sum.inl j`)        |
| `Y_i = Y₀ ⊔ ({0,…,i-1} × ℕ)`               | `Yset i`                                 |
| `K_i` = division subring generated by `Y_i` | `Kset i`                                 |
| pair `(σ, δ)` determined by `(s, d)`       | `σOf d`, `δOf d` (Proposition 3.6)       |
| triples `(f, g, e)` over `K_i` (`𝒯_i`)     | `Task i (d i)`, enumerated by `code`     |
| `⟨c, l, j⟩`                                | `enc c l j` (`Nat.pair`)                 |
| `x^τ_{l,j} = (i, ⟨c, l, j⟩)`, `X_τ`        | `xg i (d i) τ j` (the vector `x^τ_j`)    |
| `ζ` of Proposition 4.3, with `(σ_i, δ_i)`  | `zetaOf i (d i) τ`                       |
| `d_i`, `d_{i+1}` on `(i, ·)`                | `d i`, `next i (d i)` / `nextVal`        |
| `d = ⋃ d_i`, `(σ̃, δ̃)`                     | `dlim`, `σt`, `δt`                       |

(As in Remark 5.2, `d_i` is defined on all of `Y` and vanishes outside `Y_i`: `d 0 = 0`, and
`d (i+1)` only changes `d i` on the symbols `(i, ·)`. That vanishing is never used; only
`d_{i+1} = d_i` on `Y_i` is.)

The proof of Theorem 2.5 (§5) splits into:

* *Compatibility* (and the sentences of Remark 5.2 about it): `d_of_mem`, `dlim_of_mem`
  (`d_j = d = d_i` on `Y_i` for `j ≥ i`); `agree` (`(σ_i, δ_i)` and `(σ̃, δ̃)` agree on `K_i`, by
  the uniqueness part of Proposition 3.6); `inv`/`stable` (`d_i(Y_i) ⊆ K_i`, so `K_i` is stable
  under `σ_i, δ_i` by the restriction clause of Proposition 3.6); `zeta_stage_eq` (the `N_{i,j}`
  and hence `ζ` are the same for `(σ_i, δ_i)` and `(σ̃, δ̃)`); by Lemma 3.5, `exists_mem_Kset`
  (`U = ⋃ K_i`).
* *Solvability*: `solves` (Proposition 4.3 inside the tower: `g(T_f)(x^τ_0) = e` in `U`, computed
  with `(σ̃, δ̃)`) and `isCFClosed` (with the reduction of Proposition 2.2: the cases `deg f = 0`,
  `deg g = 0`, and making `f` monic).
* *Non-surjectivity*: `not_surjective` (Lemma 3.7 with `y₀ = Sum.inl 0`).
* *Countability*: the `Countable U` instance (Lemma 3.2).

The result is `exists_isCFClosed_not_surjective`, consumed by `Closure.lean`.
-/

open LeftPCI.OrePoly FreeField FreeFieldExt

namespace Tower

/-! ### The fixed set of symbols -/

/-- Remark 5.2: the fixed set of symbols `Y = Y₀ ⊔ (ℕ × ℕ)`, with `Y₀ = {y_j : j ∈ ℕ}` the
`Sum.inl j`. -/
abbrev Y : Type := ℕ ⊕ (ℕ × ℕ)

/-- Remark 5.2 / Construction 5.1: `s` is the shift `y_j ↦ y_{j+1}` on `Y₀` and the identity on
`ℕ × ℕ`. -/
def s : Y → Y := Sum.map Nat.succ id

/-- The map `s` is injective (Construction 5.1). -/
theorem s_injective : Function.Injective s :=
  Sum.map_injective.2 ⟨Nat.succ_injective, Function.injective_id⟩

/-- *Non-surjectivity* paragraph of §5: `y₀ ∉ s(Y)`. -/
theorem inl_zero_not_mem_range_s : (Sum.inl 0 : Y) ∉ Set.range s := by
  rintro ⟨y, hy⟩
  cases y with
  | inl a => simp [s] at hy
  | inr p => simp [s] at hy

@[simp] theorem s_inr (p : ℕ × ℕ) : s (Sum.inr p) = Sum.inr p := rfl

/-- Remark 5.2: `U = 𝓕(Y)` (Definition 3.4, `k = ℚ`). -/
abbrev U : Type := FreeFieldOn Y

/-- `U` is the universal field of fractions of `ℚ⟨Y⟩` (Facts 3.1). -/
theorem isUniversal : IsUniversalFieldOfFractions U (toFreeField Y) := isUniversal_toFreeField Y

/-- *Countability* paragraph of §5: `Ũ = U` is countable (Lemma 3.2). -/
instance : Countable U := FreeFieldExt.countable isUniversal

/-! ### The pairs `(σ, δ)` prescribed on generators -/

/-- The endomorphism `σ` of the pair on `U` determined by `(s, di)` (Proposition 3.6, existence;
Remark 5.2: "the pair on all of `U` determined by `(s, d_i)`"). -/
noncomputable def σOf (di : Y → U) : U →+* U := (exists_pair isUniversal s_injective di).choose

/-- The `σ`-derivation `δ` of the pair determined by `(s, di)` (Proposition 3.6). -/
noncomputable def δOf (di : Y → U) : OreDerivation U (σOf di) :=
  (exists_pair isUniversal s_injective di).choose_spec.choose

/-- Proposition 3.6: `σ(y) = s(y)` on generators. -/
theorem σOf_gen (di : Y → U) (y : Y) : σOf di (gen Y y) = gen Y (s y) :=
  (exists_pair isUniversal s_injective di).choose_spec.choose_spec.1 y

/-- Proposition 3.6: `δ(y) = d(y)` on generators. -/
theorem δOf_gen (di : Y → U) (y : Y) : δOf di (gen Y y) = di y :=
  (exists_pair isUniversal s_injective di).choose_spec.choose_spec.2 y

/-! ### The subsets `Y_i` and subfields `K_i` -/

/-- Remark 5.2: `Y_i = Y₀ ⊔ ({0, …, i-1} × ℕ)`. -/
def Yset (i : ℕ) : Set Y := Set.range Sum.inl ∪ Sum.inr '' {p | p.1 < i}

@[simp] theorem inl_mem_Yset (i a : ℕ) : (Sum.inl a : Y) ∈ Yset i := Or.inl ⟨a, rfl⟩

@[simp] theorem inr_mem_Yset (i : ℕ) (p : ℕ × ℕ) : (Sum.inr p : Y) ∈ Yset i ↔ p.1 < i := by
  simp [Yset]

/-- `Y_i ⊆ Y_{i+1}` (Construction 5.1). -/
theorem Yset_mono {i i' : ℕ} (h : i ≤ i') : Yset i ⊆ Yset i' := by
  rintro (a | p) hy
  · simp
  · simp only [inr_mem_Yset] at hy ⊢; omega

/-- `Y_i` is stable under `s` (*Compatibility* paragraph of §5). -/
theorem s_mem_Yset {i : ℕ} {y : Y} (hy : y ∈ Yset i) : s y ∈ Yset i := by
  cases y with
  | inl a => simp [s]
  | inr p => simpa using hy

/-- `Y = ⋃ Y_i` (Construction 5.1). -/
theorem exists_mem_Yset (y : Y) : ∃ i, y ∈ Yset i := by
  cases y with
  | inl a => exact ⟨0, by simp⟩
  | inr p => exact ⟨p.1 + 1, by simp⟩

/-- Remark 5.2: `K_i`, the division subring of `U` generated by `Y_i` (which is `𝓕(Y_i)` by
Lemma 3.5). -/
noncomputable def Kset (i : ℕ) : Subfield U := Subfield.closure (gen Y '' Yset i)

theorem gen_mem_Kset {i : ℕ} {y : Y} (hy : y ∈ Yset i) : gen Y y ∈ Kset i :=
  Subfield.subset_closure ⟨y, hy, rfl⟩

/-- `K_i ⊆ K_{i+1}`. -/
theorem Kset_mono {i i' : ℕ} (h : i ≤ i') : Kset i ≤ Kset i' :=
  Subfield.closure_mono (Set.image_mono (Yset_mono h))

/-- Lemma 3.5, last clause (*Compatibility* paragraph of §5): `Ũ = ⋃ K_i`, since the directed
union is a division subring containing `Y` (Lemma 3.2). -/
theorem exists_mem_Kset (u : U) : ∃ i, u ∈ Kset i := by
  have hdir : Directed (· ≤ ·) Kset := (Monotone.directed_le fun _ _ h => Kset_mono h)
  have hu : u ∈ ⨆ i, Kset i := by
    refine mem_of_forall_gen isUniversal (fun y => ?_) u
    obtain ⟨i, hi⟩ := exists_mem_Yset y
    exact (le_iSup Kset i) (gen_mem_Kset hi)
  exact (Subfield.mem_iSup_of_directed hdir).1 hu

/-- Finitely many elements of `Ũ` lie in a common `K_i` (*Solvability* paragraph of §5). -/
theorem exists_Kset_finset (S : Finset U) : ∃ i, ∀ u ∈ S, u ∈ Kset i := by
  classical
  induction S using Finset.induction with
  | empty => exact ⟨0, by simp⟩
  | insert a S _ ih =>
    obtain ⟨i, hi⟩ := ih
    obtain ⟨j, hj⟩ := exists_mem_Kset a
    refine ⟨max i j, fun u hu => ?_⟩
    rcases Finset.mem_insert.1 hu with rfl | hu
    · exact Kset_mono (le_max_right _ _) hj
    · exact Kset_mono (le_max_left _ _) (hi u hu)

/-- *Solvability* paragraph of §5: the finitely many coefficients of a polynomial lie in some
`K_i`. -/
theorem exists_Kset_coeff {σ : U →+* U} {δ : OreDerivation U σ} (p : OrePoly δ) :
    ∃ i, ∀ k, coeff δ p k ∈ Kset i := by
  classical
  obtain ⟨i, hi⟩ := exists_Kset_finset ((support δ p).image (coeff δ p))
  refine ⟨i, fun k => ?_⟩
  by_cases hk : k ∈ support δ p
  · exact hi _ (Finset.mem_image_of_mem _ hk)
  · rw [mem_support_iff, not_not] at hk
    rw [hk]; exact (Kset i).zero_mem

/-- *Solvability* paragraph of §5: the entries of `e ∈ Ũⁿ` lie in some `K_i`. -/
theorem exists_Kset_vec {n : ℕ} (v : Fin n → U) : ∃ i, ∀ l, v l ∈ Kset i := by
  classical
  obtain ⟨i, hi⟩ := exists_Kset_finset (Finset.univ.image v)
  exact ⟨i, fun l => hi _ (Finset.mem_image_of_mem _ (Finset.mem_univ l))⟩

/-! ### Tasks -/

/-- A polynomial over one pair, viewed over another (`OrePoly δ` is `ℕ →₀ U` for every `δ`).
This is the identification of `R_i`'s underlying coefficient sequences with those of `R̃` in the
*Compatibility* paragraph of §5. -/
def recast {σ σ' : U →+* U} {δ : OreDerivation U σ} (δ' : OreDerivation U σ') (p : OrePoly δ) :
    OrePoly δ' := p

/-- Construction 5.1 / Remark 5.2: the set `𝒯_i` of triples `(f, g, e)` over `K_i`, with `f` monic of
degree `n ≥ 1`, `deg g ≥ 1` and `e ∈ K_iⁿ` (polynomials over `U` with coefficients in `K_i`,
written with the pair `(σ_i, δ_i)`). -/
structure Task (i : ℕ) (di : Y → U) where
  f : OrePoly (δOf di)
  g : OrePoly (δOf di)
  e : Fin (natDegree (δOf di) f) → U
  f_monic : leadingCoeff (δOf di) f = 1
  f_deg : 0 < natDegree (δOf di) f
  g_deg : 0 < natDegree (δOf di) g
  f_mem : ∀ k, coeff (δOf di) f k ∈ Kset i
  g_mem : ∀ k, coeff (δOf di) g k ∈ Kset i
  e_mem : ∀ l, e l ∈ Kset i

/-- *Countability* paragraph of §5 / Remark 5.2: `𝒯_i` is countable. -/
instance (i : ℕ) (di : Y → U) : Countable (Task i di) := by
  have : Countable (OrePoly (δOf di)) := inferInstanceAs (Countable (ℕ →₀ U))
  refine Function.Injective.countable
    (f := fun τ : Task i di => (τ.f, τ.g, (⟨_, τ.e⟩ : Σ n, Fin n → U))) ?_
  rintro ⟨f, g, e, _, _, _, _, _, _⟩ ⟨f', g', e', _, _, _, _, _, _⟩ h
  simp only [Prod.mk.injEq] at h
  obtain ⟨rfl, rfl, h⟩ := h
  cases h
  rfl

/-- Remark 5.2: "enumerate the (countably many) triples `(f, g, e)` over `K_i` by natural numbers
`c`" (an injection `𝒯_i → ℕ`). -/
noncomputable def code (i : ℕ) (di : Y → U) : Task i di → ℕ :=
  (Countable.exists_injective_nat (Task i di)).choose

/-- The enumeration is injective. -/
theorem code_injective (i : ℕ) (di : Y → U) : Function.Injective (code i di) :=
  (Countable.exists_injective_nat (Task i di)).choose_spec

/-- Remark 5.2: the pairing function `⟨c, l, j⟩`. -/
def enc (c l j : ℕ) : ℕ := Nat.pair c (Nat.pair l j)

/-- Remark 5.2: the symbols `(i, ⟨c, l, j⟩)` play the role of `x^τ_{l,j}`; this is the row vector
`x^τ_j = (x^τ_{1,j}, …, x^τ_{n,j})` of Proposition 4.3 (`c` = the code of `τ`). -/
noncomputable def xg (i : ℕ) (di : Y → U) (τ : Task i di) (j : ℕ) :
    Fin (natDegree (δOf di) τ.f) → U :=
  fun l => gen Y (Sum.inr (i, enc (code i di τ) l j))

/-- Proposition 4.3: `ζ = g_m⁻¹(e − Φ)` for the task `τ`, computed with `(σ_i, δ_i)` (Remark 5.2). -/
noncomputable def zetaOf (i : ℕ) (di : Y → U) (τ : Task i di) :
    Fin (natDegree (δOf di) τ.f) → U :=
  Adjoin.zeta (δOf di) (Adjoin.companion (δOf di) τ.f) τ.g (fun j => xg i di τ j) τ.e

/-- The recipe of Proposition 4.3 for the task `τ`: `d'(x_{l,j}) = x_{l,j+1}` for `j ≤ m − 2` and
`d'(x_{l,m−1}) = ζ_l`; other indices get `0` (Remark 5.2: unused symbols). -/
noncomputable def nextValOf (i : ℕ) (di : Y → U) (τ : Task i di) (l j : ℕ) : U :=
  if hl : l < natDegree (δOf di) τ.f then
    if j + 1 < natDegree (δOf di) τ.g then xg i di τ (j + 1) ⟨l, hl⟩
    else if j + 1 = natDegree (δOf di) τ.g then zetaOf i di τ ⟨l, hl⟩ else 0
  else 0

open Classical in
/-- Remark 5.2: the value of `d_{i+1}` on the symbol `(i, ⟨c, l, j⟩)`: the recipe of Proposition 4.3
if `c` codes a task, `0` otherwise. -/
noncomputable def nextVal (i : ℕ) (di : Y → U) (c l j : ℕ) : U :=
  if h : ∃ τ : Task i di, code i di τ = c then nextValOf i di h.choose l j else 0

/-- Decoding: on the code of `τ`, `nextVal` follows the recipe for `τ`. -/
theorem nextVal_code (i : ℕ) (di : Y → U) (τ : Task i di) (l j : ℕ) :
    nextVal i di (code i di τ) l j = nextValOf i di τ l j := by
  have h : ∃ τ' : Task i di, code i di τ' = code i di τ := ⟨τ, rfl⟩
  simp only [nextVal, h, ↓reduceDIte]
  rw [code_injective i di h.choose_spec]

/-- Remark 5.2: `d_{i+1}` is `d_i` away from the symbols `(i, ·)`, and is given by `nextVal` on
them (and `0` on `Y₀`, where `d_0 = 0`). -/
noncomputable def next (i : ℕ) (di : Y → U) : Y → U
  | Sum.inl _ => 0
  | Sum.inr (i', c') =>
    if i' = i then
      nextVal i di (Nat.unpair c').1 (Nat.unpair (Nat.unpair c').2).1
        (Nat.unpair (Nat.unpair c').2).2
    else di (Sum.inr (i', c'))

/-- Decoding with `Nat.unpair_pair`. -/
theorem next_enc (i : ℕ) (di : Y → U) (c l j : ℕ) :
    next i di (Sum.inr (i, enc c l j)) = nextVal i di c l j := by
  simp [next, enc, Nat.unpair_pair]

/-- Remark 5.2: the maps `d_i : Y → U`, with `d_0 = 0`. -/
noncomputable def d : ℕ → Y → U
  | 0 => 0
  | i + 1 => next i (d i)

/-- `d_i = d_0 = 0` on `Y₀` (Construction 5.1). -/
@[simp] theorem d_inl (i a : ℕ) : d i (Sum.inl a) = 0 := by
  cases i <;> rfl

/-- Remark 5.2: `d_{i+1} = d_i` on `Y_i`. -/
theorem d_succ_of_mem {i : ℕ} {y : Y} (hy : y ∈ Yset i) : d (i + 1) y = d i y := by
  cases y with
  | inl a => simp
  | inr p =>
    obtain ⟨a, c⟩ := p
    simp only [inr_mem_Yset] at hy
    simp [d, next, Nat.ne_of_lt hy]

/-- Remark 5.2: `d_j = d_i` on `Y_i` for `j ≥ i`. -/
theorem d_of_mem {i i' : ℕ} (h : i ≤ i') {y : Y} (hy : y ∈ Yset i) : d i' y = d i y := by
  induction i', h using Nat.le_induction with
  | base => rfl
  | succ i' hi ih => rw [d_succ_of_mem (Yset_mono hi hy), ih]

/-- Remark 5.2: `d = ⋃ d_i` (the symbol `(j, c)` enters at stage `j + 1`). -/
noncomputable def dlim : Y → U
  | Sum.inl _ => 0
  | Sum.inr (j, c) => d (j + 1) (Sum.inr (j, c))

/-- Remark 5.2: `d = d_i` on `Y_i`. -/
theorem dlim_of_mem {i : ℕ} {y : Y} (hy : y ∈ Yset i) : dlim y = d i y := by
  cases y with
  | inl a => simp [dlim]
  | inr p =>
    obtain ⟨a, c⟩ := p
    simp only [inr_mem_Yset] at hy
    exact (d_of_mem (Nat.succ_le_of_lt hy) (by simp)).symm

/-- `σ̃`, of the pair `(σ̃, δ̃)` determined by `(s, d)` (Construction 5.1, Remark 5.2). -/
noncomputable abbrev σt : U →+* U := σOf dlim
/-- `δ̃`, the `σ̃`-derivation of the pair determined by `(s, d)`. -/
noncomputable abbrev δt : OreDerivation U σt := δOf dlim

/-! ### Compatibility -/

/-- Remark 5.2 / *Compatibility* paragraph of §5: since `d_i = d` on `Y_i`, the pairs
`(σ_i, δ_i)` and `(σ̃, δ̃)` agree on `K_i` (uniqueness part of Proposition 3.6). -/
theorem agree (i : ℕ) : ∀ u ∈ Kset i, σOf (d i) u = σt u ∧ δOf (d i) u = δt u :=
  agree_closure (δOf (d i)) δt
    (by rintro _ ⟨y, -, rfl⟩; rw [σOf_gen, σOf_gen])
    (by rintro _ ⟨y, hy, rfl⟩; rw [δOf_gen, δOf_gen, dlim_of_mem hy])

/-- Restriction clause of Proposition 3.6: if `d_i(Y_i) ⊆ K_i` then `K_i` is stable under
`σ_i, δ_i`. -/
theorem stable_of_inv {i : ℕ} (h : ∀ y ∈ Yset i, d i y ∈ Kset i) :
    ∀ u ∈ Kset i, σOf (d i) u ∈ Kset i ∧ δOf (d i) u ∈ Kset i :=
  stable_closure (δOf (d i))
    (by rintro _ ⟨y, hy, rfl⟩; rw [σOf_gen]; exact gen_mem_Kset (s_mem_Yset hy))
    (by rintro _ ⟨y, hy, rfl⟩; rw [δOf_gen]; exact h y hy)

/-- The values `ζ_l` for a task at stage `i` lie in `K_{i+1}` (Construction 5.1: "its values lie in
`𝓕(Y_i ⊔ X_τ) ⊆ 𝓕(Y_{i+1})`"): `e`, the `g_i` and the `N_{i,j}` are over `K_i`, and the `x_j`
are generators in `Y_{i+1}`. -/
theorem zetaOf_mem {i : ℕ}
    (hst : ∀ u ∈ Kset i, σOf (d i) u ∈ Kset i ∧ δOf (d i) u ∈ Kset i)
    (τ : Task i (d i)) (l : Fin (natDegree (δOf (d i)) τ.f)) :
    zetaOf i (d i) τ l ∈ Kset (i + 1) := by
  set K1 := Kset (i + 1)
  have hle : Kset i ≤ K1 := Kset_mono (Nat.le_succ i)
  have hx : ∀ j a, xg i (d i) τ j a ∈ K1 := fun j a => gen_mem_Kset (by simp)
  have hN : ∀ p q a b, Adjoin.Nmat (δOf (d i)) (Adjoin.companion (δOf (d i)) τ.f) p q a b ∈ K1 :=
    fun p q a b => hle (Adjoin.Nmat_mem _ _ (Kset i)
      (Adjoin.companion_mem _ τ.f (Kset i) τ.f_mem) hst p q a b)
  have hPhi : ∀ l, Adjoin.Phi (δOf (d i)) (Adjoin.companion (δOf (d i)) τ.f) τ.g
      (fun j => xg i (d i) τ j) l ∈ K1 := by
    intro l
    unfold Adjoin.Phi
    rw [Finset.sum_apply]
    refine K1.sum_mem fun p _ => ?_
    rw [Pi.smul_apply, smul_eq_mul, Finset.sum_apply]
    refine K1.mul_mem (hle (τ.g_mem p)) (K1.sum_mem fun q _ => ?_)
    simp only [Matrix.vecMul, dotProduct]
    exact K1.sum_mem fun a _ => K1.mul_mem (hx _ _) (hN _ _ _ _)
  unfold zetaOf Adjoin.zeta
  rw [Pi.smul_apply, smul_eq_mul, Pi.sub_apply]
  exact K1.mul_mem (K1.inv_mem (hle (τ.g_mem _))) (K1.sub_mem (hle (τ.e_mem l)) (hPhi l))

/-- `d_{i+1}` maps the new symbols `(i, ·)` into `K_{i+1}`. -/
theorem nextVal_mem {i : ℕ}
    (hst : ∀ u ∈ Kset i, σOf (d i) u ∈ Kset i ∧ δOf (d i) u ∈ Kset i) (c l j : ℕ) :
    nextVal i (d i) c l j ∈ Kset (i + 1) := by
  unfold nextVal nextValOf
  split_ifs
  · exact gen_mem_Kset (by simp)
  · exact zetaOf_mem hst _ _
  all_goals exact (Kset (i + 1)).zero_mem

/-- `d_i(Y_i) ⊆ K_i` (Construction 5.1: `d_i : Y_i → 𝓕(Y_i)`), by induction on `i`. -/
theorem inv : ∀ i, ∀ y ∈ Yset i, d i y ∈ Kset i
  | 0, y, _ => (Kset 0).zero_mem
  | i + 1, y, hy => by
    by_cases hyi : y ∈ Yset i
    · rw [d_succ_of_mem hyi]; exact Kset_mono (Nat.le_succ i) (inv i y hyi)
    · rcases y with a | ⟨a, c'⟩
      · simp at hyi
      · simp only [inr_mem_Yset] at hy hyi
        have ha : a = i := by omega
        subst ha
        have hc : c' = enc (Nat.unpair c').1 (Nat.unpair (Nat.unpair c').2).1
            (Nat.unpair (Nat.unpair c').2).2 := by simp [enc, Nat.pair_unpair]
        rw [hc]
        change next a (d a) _ ∈ _
        rw [next_enc]
        exact nextVal_mem (stable_of_inv (inv a)) _ _ _

/-- Remark 5.2: `K_i` is stable under `σ_i, δ_i`, by the restriction clause of Proposition 3.6. -/
theorem stable (i : ℕ) : ∀ u ∈ Kset i, σOf (d i) u ∈ Kset i ∧ δOf (d i) u ∈ Kset i :=
  stable_of_inv (inv i)

/-! ### Solvability -/

/-- The degree does not depend on the pair. -/
@[simp] theorem natDegree_recast {σ σ' : U →+* U} {δ : OreDerivation U σ}
    (δ' : OreDerivation U σ') (p : OrePoly δ) : natDegree δ' (recast δ' p) = natDegree δ p := rfl

/-- Remark 5.2: the matrices `N_{i,j}` of Proposition 4.3, whose entries lie in `K_i`, are the same
whether computed with `(σ_i, δ_i)` or with `(σ̃, δ̃)`; hence so is `ζ`. -/
theorem zeta_stage_eq (i : ℕ) (τ : Task i (d i)) :
    zetaOf i (d i) τ = Adjoin.zeta δt (Adjoin.companion δt (recast δt τ.f)) (recast δt τ.g)
      (fun j => xg i (d i) τ j) τ.e := by
  have hN := Adjoin.Nmat_congr (δOf (d i)) (Adjoin.companion (δOf (d i)) τ.f) δt (Kset i)
    (Adjoin.companion_mem _ τ.f (Kset i) τ.f_mem) (stable i) (agree i)
  unfold zetaOf Adjoin.zeta Adjoin.Phi
  simp only [hN]
  rfl

/-- *Solvability* paragraph of §5: Proposition 4.3 applied inside the tower. For a task
`τ = (f, g, e) ∈ 𝒯_i`, the vector `v = x^τ_0` satisfies `g(T_f)(v) = e` in `Ũⁿ`, with `T_f`
computed with `(σ̃, δ̃)`: `σ̃` fixes the `x^τ_j`, `δ̃(x^τ_j) = x^τ_{j+1}` for `j ≤ m − 2`, and
`δ̃(x^τ_{m−1}) = ζ` (by compatibility). -/
theorem solves (i : ℕ) (τ : Task i (d i)) :
    Adjoin.evalT δt (Adjoin.companion δt (recast δt τ.f)) (recast δt τ.g) (xg i (d i) τ 0) = τ.e := by
  set C := Adjoin.companion δt (recast δt τ.f)
  set G := recast δt τ.g
  have hm : 0 < natDegree δt G := τ.g_deg
  set ζ := Adjoin.zeta δt C G (fun j => xg i (d i) τ j) τ.e with hζdef
  let x : ℕ → Fin (natDegree (δOf (d i)) τ.f) → U := fun j =>
    if j < natDegree δt G then xg i (d i) τ j else ζ
  have hx : ∀ j < natDegree δt G, x j = xg i (d i) τ j := fun j hj => by simp only [x, hj, ↓reduceIte]
  have hxm : x (natDegree δt G) = ζ := by simp only [x, lt_irrefl, ↓reduceIte]; rfl
  have h := Adjoin.evalT_eq δt C G hm x τ.e
    (fun j hj => by
      rw [hx j hj]; funext l
      exact σOf_gen dlim _)
    (fun j hj => by
      rw [hx j hj]; funext (l : Fin (natDegree (δOf (d i)) τ.f))
      change δt (gen Y (Sum.inr (i, enc (code i (d i) τ) l j))) = x (j + 1) l
      rw [δOf_gen, dlim_of_mem (i := i + 1) (by simp)]
      change next i (d i) _ = _
      rw [next_enc, nextVal_code, nextValOf]
      simp only [l.2, ↓reduceDIte]
      split_ifs with h1 h2
      · rw [hx _ h1]
      · have : j + 1 = natDegree δt G := h2
        rw [this, hxm, zeta_stage_eq]
      · exact absurd hj (by change ¬ j < natDegree (δOf (d i)) τ.g; omega))
    (by rw [hxm, hζdef]; exact Adjoin.zeta_congr δt C G hm (fun j hj => (hx j hj).symm) τ.e)
  rwa [hx 0 hm] at h

/-! ### The theorem -/

section CMul

variable {σ : U →+* U} {δ : OreDerivation U σ}

/-- Left multiplication by a nonzero constant preserves the support (used to make `f` monic,
Proposition 2.2: `f = a f₁`). -/
theorem support_C_mul {a : U} (ha : a ≠ 0) (f : OrePoly δ) :
    support δ (C δ a * f) = support δ f := by
  ext n
  rw [mem_support_iff, mem_support_iff, coeff_C_mul, mul_ne_zero_iff_left ha]

/-- `deg (a f) = deg f` for `a ≠ 0`. -/
theorem natDegree_C_mul {a : U} (ha : a ≠ 0) (f : OrePoly δ) :
    natDegree δ (C δ a * f) = natDegree δ f := by
  unfold natDegree
  rw [support_C_mul ha]

/-- The leading coefficient of `a f` is `a · lc f` for `a ≠ 0`. -/
theorem leadingCoeff_C_mul {a : U} (ha : a ≠ 0) (f : OrePoly δ) :
    leadingCoeff δ (C δ a * f) = a * leadingCoeff δ f := by
  unfold leadingCoeff
  rw [natDegree_C_mul ha, coeff_C_mul]

end CMul

/-- **Theorem 2.5, solvability** (proved in §5), in the form needed by Baer's criterion after
Proposition 2.2: every proper cyclic left `Ũ[t; σ̃, δ̃]`-module is divisible. The cases
`deg f = 0` (`Rf = R`) and `deg g = 0` (`g` a unit) are as in the proof of Proposition 2.2; otherwise
`f = a f₁` with `f₁` monic, all coefficients of `f₁, g` and of `e = m̄` lie in some `K_i`
(*Solvability* paragraph of §5), `solves` gives `g(T_{f₁})(v) = m̄`, and Lemma 2.1 converts this to
`m ≡ g b (mod R f₁ = R f)`. -/
theorem isCFClosed : IsCFClosed δt := by
  intro f hf g hg m
  -- trivial case: `f` is a nonzero constant
  by_cases hf0 : natDegree δt f = 0
  · have hfC := eq_C_of_natDegree_eq_zero δt hf0
    set c := coeff δt f 0
    have hc : c ≠ 0 := by
      intro hc
      exact hf (by rw [hfC, hc, map_zero])
    refine ⟨0, Ideal.mem_span_singleton'.mpr ⟨m * C δt c⁻¹, ?_⟩⟩
    rw [hfC, mul_assoc, ← map_mul, inv_mul_cancel₀ hc, map_one, mul_one, mul_zero, sub_zero]
  -- trivial case: `g` is a nonzero constant
  by_cases hg0 : natDegree δt g = 0
  · have hgC := eq_C_of_natDegree_eq_zero δt hg0
    set c := coeff δt g 0
    have hc : c ≠ 0 := by
      intro hc
      exact hg (by rw [hgC, hc, map_zero])
    refine ⟨C δt c⁻¹ * m, ?_⟩
    rw [hgC, ← mul_assoc, ← map_mul, mul_inv_cancel₀ hc, map_one, one_mul, sub_self]
    exact zero_mem _
  -- make `f` monic
  have hlc : leadingCoeff δt f ≠ 0 := leadingCoeff_ne_zero δt hf
  have hlc' : (leadingCoeff δt f)⁻¹ ≠ 0 := inv_ne_zero hlc
  set f₁ := C δt (leadingCoeff δt f)⁻¹ * f with hf₁
  have hmon : leadingCoeff δt f₁ = 1 := by rw [leadingCoeff_C_mul hlc', inv_mul_cancel₀ hlc]
  have hdeg : 0 < natDegree δt f₁ := by rw [natDegree_C_mul hlc']; omega
  have hf₁0 : f₁ ≠ 0 := ne_zero_of_leadingCoeff_ne_zero δt (by rw [hmon]; exact one_ne_zero)
  set e := Adjoin.remVec δt f₁ hf₁0 m
  -- descend to a stage `i`
  obtain ⟨i₁, h₁⟩ := exists_Kset_coeff f₁
  obtain ⟨i₂, h₂⟩ := exists_Kset_coeff g
  obtain ⟨i₃, h₃⟩ := exists_Kset_vec e
  set i := max i₁ (max i₂ i₃)
  let τ : Task i (d i) :=
    { f := recast (δOf (d i)) f₁
      g := recast (δOf (d i)) g
      e := e
      f_monic := hmon
      f_deg := hdeg
      g_deg := by change 0 < natDegree δt g; omega
      f_mem := fun k => Kset_mono (le_max_left _ _) (h₁ k)
      g_mem := fun k => Kset_mono ((le_max_left _ _).trans (le_max_right _ _)) (h₂ k)
      e_mem := fun l => Kset_mono ((le_max_right _ _).trans (le_max_right _ _)) (h₃ l) }
  have hv : Adjoin.evalT δt (Adjoin.companion δt f₁) g (xg i (d i) τ 0) =
      Adjoin.remVec δt f₁ hf₁0 m := solves i τ
  have hmem := Adjoin.sub_mul_mem_of_evalT_eq δt f₁ hmon hdeg hf₁0 g m _ hv
  refine ⟨Adjoin.ofVec δt (xg i (d i) τ 0), ?_⟩
  obtain ⟨c, hc⟩ := Ideal.mem_span_singleton'.mp hmem
  refine Ideal.mem_span_singleton'.mpr ⟨c * C δt (leadingCoeff δt f)⁻¹, ?_⟩
  rw [mul_assoc]
  exact hc

/-- *Non-surjectivity* paragraph of §5: `y₀ ∉ s(Y)`, so `y₀ ∉ σ̃(Ũ)` by Lemma 3.7. -/
theorem not_surjective : ¬ Function.Surjective σt := fun h =>
  gen_not_mem_range isUniversal s_injective inl_zero_not_mem_range_s (σOf_gen dlim)
    (h (gen Y (Sum.inl 0)))

end Tower

/-- **Theorem 2.5** (with `k = ℚ`, proved in §5 via Construction 5.1 / Remark 5.2): a countable
division ring `K̃` with a non-surjective endomorphism `σ̃` and a `σ̃`-derivation `δ̃` such that
every equation `g(T_f)(v) = e` is solvable, in the equivalent form `IsCFClosed δ̃` (every proper
cyclic left `K̃[t; σ̃, δ̃]`-module is divisible). -/
theorem exists_isCFClosed_not_surjective :
    ∃ (K : Type) (_ : DivisionRing K) (σ : K →+* K) (δ : OreDerivation K σ),
      Countable K ∧ ¬ Function.Surjective σ ∧ IsCFClosed δ :=
  ⟨Tower.U, inferInstance, Tower.σt, Tower.δt, inferInstance, Tower.not_surjective,
    Tower.isCFClosed⟩

end LeftPCI.Counterexample
